# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 23:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Expedition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expeditionStartDate', models.CharField(max_length=200)),
                ('expeditionEndDate', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationCode', models.CharField(max_length=200)),
                ('locationName', models.CharField(max_length=200)),
                ('locationLat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('locationLong', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observationLegacyID', models.CharField(max_length=200)),
                ('observationDate', models.DateTimeField(auto_now_add=True)),
                ('pondLocation', models.CharField(max_length=400)),
                ('recaptured', models.BooleanField(default=0)),
                ('trapType', models.CharField(max_length=200)),
                ('bait', models.CharField(max_length=200)),
                ('ageInYears', models.CharField(max_length=200)),
                ('massInGrams', models.DecimalField(decimal_places=3, max_digits=8)),
                ('carapaceLengthCM', models.DecimalField(decimal_places=3, max_digits=8)),
                ('carapaceWidthCM', models.DecimalField(decimal_places=3, max_digits=8)),
                ('carapaceHeightCM', models.DecimalField(decimal_places=3, max_digits=8)),
                ('plastronLengthCM', models.DecimalField(decimal_places=3, max_digits=8)),
                ('observationNotes', models.TextField(max_length=1000)),
                ('expeditionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turtle_observer.Expedition')),
                ('locationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turtle_observer.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Observer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observerCode', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Turtle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turtlePitTagID', models.CharField(max_length=200)),
                ('turtleSpecies', models.CharField(max_length=200)),
                ('turtleSex', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='observation',
            name='turtleID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turtle_observer.Turtle'),
        ),
    ]
