# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-15 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turtle_observer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expedition',
            name='expeditionEndDate',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='expedition',
            name='expeditionStartDate',
            field=models.DateTimeField(),
        ),
    ]
