# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-16 01:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turtle_observer', '0002_auto_20160615_2312'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpeditionLocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expeditionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turtle_observer.Expedition')),
                ('locationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turtle_observer.Location')),
            ],
        ),
        migrations.CreateModel(
            name='ExpeditionObserver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expeditionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turtle_observer.Expedition')),
                ('observerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turtle_observer.Observer')),
            ],
        ),
        migrations.CreateModel(
            name='ObservationObserver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turtle_observer.Observation')),
                ('observerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='turtle_observer.Observer')),
            ],
        ),
    ]
