# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-17 15:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turtle_observer', '0005_auto_20160617_1438'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expeditionlocation',
            old_name='expeditionID',
            new_name='expedition_id',
        ),
        migrations.RenameField(
            model_name='expeditionlocation',
            old_name='locationID',
            new_name='location_id',
        ),
    ]
