# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-06 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('turtle_observer', '0007_auto_20160617_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observation',
            name='location_id',
        ),
        migrations.RemoveField(
            model_name='observer',
            name='observer_code',
        ),
        migrations.AddField(
            model_name='observation',
            name='location',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='turtle_observer.Location'),
        ),
        migrations.AddField(
            model_name='observer',
            name='observer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='observation_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
