# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-17 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turtle_observer', '0008_auto_20160706_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expeditionlocation',
            name='expedition',
        ),
        migrations.RemoveField(
            model_name='expeditionlocation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='expeditionobserver',
            name='expedition',
        ),
        migrations.RemoveField(
            model_name='expeditionobserver',
            name='observer',
        ),
        migrations.RemoveField(
            model_name='observationobserver',
            name='observation',
        ),
        migrations.RemoveField(
            model_name='observationobserver',
            name='observer',
        ),
        migrations.AddField(
            model_name='expedition',
            name='locations',
            field=models.ManyToManyField(to='turtle_observer.Location'),
        ),
        migrations.AddField(
            model_name='observation',
            name='observers',
            field=models.ManyToManyField(to='turtle_observer.Observer'),
        ),
        migrations.AddField(
            model_name='observer',
            name='expeditions',
            field=models.ManyToManyField(to='turtle_observer.Expedition'),
        ),
        migrations.DeleteModel(
            name='ExpeditionLocation',
        ),
        migrations.DeleteModel(
            name='ExpeditionObserver',
        ),
        migrations.DeleteModel(
            name='ObservationObserver',
        ),
    ]
