# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-17 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turtle_observer', '0009_auto_20160717_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='ordinal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='age_in_years',
            field=models.CharField(blank=True, choices=[('Juvenile', 'Juvenile'), ('1', '1 year'), ('2', '2 years'), ('3', '3 years'), ('4', '4 years'), ('Adult', 'Adult'), ('5', '5 years'), ('6', '6 years'), ('7', '7 years'), ('8', '8 years'), ('9', '9 years'), ('10', '10 years'), ('10+', 'Over 10 years'), ('Worn', 'Worn')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='trap_type',
            field=models.CharField(blank=True, choices=[('hoop', 'Hoop Trap'), ('bask-m', 'Basking Trap M'), ('bask-p', 'Basking Trap P'), ('snrkl', 'By Snorkeling'), ('hand', 'By Hand')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='turtle',
            name='turtle_sex',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='turtle',
            name='turtle_species',
            field=models.CharField(blank=True, choices=[('Cpp', 'Eastern Painted (Chrysemys picta picta)'), ('Css', 'Eastern Snapping (Chelydra serpentina serpentina)'), ('Tcc', 'Eastern Box (Terrapene carolina carolina)'), ('Tse', 'Red-eared Slider (Trachemys scripta elegans)'), ('O', 'Other'), ('U', 'Unknown')], max_length=200, null=True),
        ),
    ]
