# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-17 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turtle_observer', '0010_auto_20160717_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='ordinal',
        ),
    ]
