# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-08-14 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turtle_observer', '0012_auto_20160728_0318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='observation',
            old_name='pond_location',
            new_name='location_in_pond',
        ),
        migrations.AddField(
            model_name='expedition',
            name='expedition_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='observation',
            name='trap_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='observation',
            name='trap_type',
            field=models.CharField(blank=True, choices=[('hoop', 'Hoop Trap'), ('bask-m', 'Basking Trap Metal'), ('bask-p', 'Basking Trap Polystyrene'), ('snrkl', 'By Snorkeling'), ('hand', 'By Hand')], max_length=200, null=True),
        ),
    ]
